// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /me/balance"
  | "GET /me/merchant"
  | "GET /me/payment-requests"
  | "GET /me/payment-requests/{paymentRequestId}"
  | "GET /me/payouts"
  | "GET /me/transactions"
  | "GET /payment-links/{paymentRequestId}"
  | "POST /me/merchant"
  | "POST /me/payment-requests"
  | "POST /me/payouts"
  | "POST /payment-links/{paymentRequestId}/pay";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /me/balance": { kind: "scope", scope: "transactions:read" },
  "GET /me/merchant": { kind: "signedIn" },
  "GET /me/payment-requests": { kind: "scope", scope: "payment-requests:read" },
  "GET /me/payment-requests/{paymentRequestId}": { kind: "scope", scope: "payment-requests:read" },
  "GET /me/payouts": { kind: "scope", scope: "payouts:read" },
  "GET /me/transactions": { kind: "scope", scope: "transactions:read" },
  "GET /payment-links/{paymentRequestId}": { kind: "public" },
  "POST /me/merchant": { kind: "signedIn" },
  "POST /me/payment-requests": { kind: "scope", scope: "payment-requests:create" },
  "POST /me/payouts": { kind: "scope", scope: "payouts:request" },
  "POST /payment-links/{paymentRequestId}/pay": { kind: "public" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
